export const COUNTRIES = [
  { name: 'Afghanistan', alpha2: 'af' },
  { name: 'Albania', alpha2: 'al' },
  { name: 'Algeria', alpha2: 'dz' },
  { name: 'Andorra', alpha2: 'ad' },
  { name: 'Angola', alpha2: 'ao' },
  { name: 'Antigua and Barbuda', alpha2: 'ag' },
  { name: 'Argentina', alpha2: 'ar' },
  { name: 'Armenia', alpha2: 'am' },
  { name: 'Australia', alpha2: 'au' },
  { name: 'Austria', alpha2: 'at' },
  { name: 'Azerbaijan', alpha2: 'az' },
  { name: 'Bahamas', alpha2: 'bs' },
  { name: 'Bahrain', alpha2: 'bh' },
  { name: 'Bangladesh', alpha2: 'bd' },
  { name: 'Barbados', alpha2: 'bb' },
  { name: 'Belarus', alpha2: 'by' },
  { name: 'Belgium', alpha2: 'be' },
  { name: 'Belize', alpha2: 'bz' },
  { name: 'Benin', alpha2: 'bj' },
  { name: 'Bhutan', alpha2: 'bt' },
  { name: 'Bolivia', alpha2: 'bo' },
  { name: 'Bosnia and Herzegovina', alpha2: 'ba' },
  { name: 'Botswana', alpha2: 'bw' },
  { name: 'Brazil', alpha2: 'br' },
  { name: 'Brunei', alpha2: 'bn' },
  { name: 'Bulgaria', alpha2: 'bg' },
  { name: 'Burkina Faso', alpha2: 'bf' },
  { name: 'Burundi', alpha2: 'bi' },
  { name: 'Cabo Verde', alpha2: 'cv' },
  { name: 'Cambodia', alpha2: 'kh' },
  { name: 'Cameroon', alpha2: 'cm' },
  { name: 'Canada', alpha2: 'ca' },
  { name: 'Central African Republic', alpha2: 'cf' },
  { name: 'Chad', alpha2: 'td' },
  { name: 'Chile', alpha2: 'cl' },
  { name: 'China', alpha2: 'cn' },
  { name: 'Colombia', alpha2: 'co' },
  { name: 'Comoros', alpha2: 'km' },
  { name: 'Congo (DRC)', alpha2: 'cd' },
  { name: 'Congo (Republic)', alpha2: 'cg' },
  { name: 'Costa Rica', alpha2: 'cr' },
  { name: 'Croatia', alpha2: 'hr' },
  { name: 'Cuba', alpha2: 'cu' },
  { name: 'Cyprus', alpha2: 'cy' },
  { name: 'Czech Republic', alpha2: 'cz' },
  { name: 'Denmark', alpha2: 'dk' },
  { name: 'Djibouti', alpha2: 'dj' },
  { name: 'Dominica', alpha2: 'dm' },
  { name: 'Dominican Republic', alpha2: 'do' },
  { name: 'East Timor', alpha2: 'tl' },
  { name: 'Ecuador', alpha2: 'ec' },
  { name: 'Egypt', alpha2: 'eg' },
  { name: 'El Salvador', alpha2: 'sv' },
  { name: 'Equatorial Guinea', alpha2: 'gq' },
  { name: 'Eritrea', alpha2: 'er' },
  { name: 'Estonia', alpha2: 'ee' },
  { name: 'Eswatini', alpha2: 'sz' },
  { name: 'Ethiopia', alpha2: 'et' },
  { name: 'Fiji', alpha2: 'fj' },
  { name: 'Finland', alpha2: 'fi' },
  { name: 'France', alpha2: 'fr' },
  { name: 'Gabon', alpha2: 'ga' },
  { name: 'Gambia', alpha2: 'gm' },
  { name: 'Georgia', alpha2: 'ge' },
  { name: 'Germany', alpha2: 'de' },
  { name: 'Ghana', alpha2: 'gh' },
  { name: 'Greece', alpha2: 'gr' },
  { name: 'Grenada', alpha2: 'gd' },
  { name: 'Guatemala', alpha2: 'gt' },
  { name: 'Guinea', alpha2: 'gn' },
  { name: 'Guinea-Bissau', alpha2: 'gw' },
  { name: 'Guyana', alpha2: 'gy' },
  { name: 'Haiti', alpha2: 'ht' },
  { name: 'Honduras', alpha2: 'hn' },
  { name: 'Hungary', alpha2: 'hu' },
  { name: 'Iceland', alpha2: 'is' },
  { name: 'India', alpha2: 'in' },
  { name: 'Indonesia', alpha2: 'id' },
  { name: 'Iran', alpha2: 'ir' },
  { name: 'Iraq', alpha2: 'iq' },
  { name: 'Ireland', alpha2: 'ie' },
  { name: 'Israel', alpha2: 'il' },
  { name: 'Italy', alpha2: 'it' },
  { name: 'Ivory Coast', alpha2: 'ci' },
  { name: 'Jamaica', alpha2: 'jm' },
  { name: 'Japan', alpha2: 'jp' },
  { name: 'Jordan', alpha2: 'jo' },
  { name: 'Kazakhstan', alpha2: 'kz' },
  { name: 'Kenya', alpha2: 'ke' },
  { name: 'Kiribati', alpha2: 'ki' },
  { name: 'Kosovo', alpha2: 'xk' },
  { name: 'Kuwait', alpha2: 'kw' },
  { name: 'Kyrgyzstan', alpha2: 'kg' },
  { name: 'Laos', alpha2: 'la' },
  { name: 'Latvia', alpha2: 'lv' },
  { name: 'Lebanon', alpha2: 'lb' },
  { name: 'Lesotho', alpha2: 'ls' },
  { name: 'Liberia', alpha2: 'lr' },
  { name: 'Libya', alpha2: 'ly' },
  { name: 'Liechtenstein', alpha2: 'li' },
  { name: 'Lithuania', alpha2: 'lt' },
  { name: 'Luxembourg', alpha2: 'lu' },
  { name: 'Madagascar', alpha2: 'mg' },
  { name: 'Malawi', alpha2: 'mw' },
  { name: 'Malaysia', alpha2: 'my' },
  { name: 'Maldives', alpha2: 'mv' },
  { name: 'Mali', alpha2: 'ml' },
  { name: 'Malta', alpha2: 'mt' },
  { name: 'Marshall Islands', alpha2: 'mh' },
  { name: 'Mauritania', alpha2: 'mr' },
  { name: 'Mauritius', alpha2: 'mu' },
  { name: 'Mexico', alpha2: 'mx' },
  { name: 'Micronesia', alpha2: 'fm' },
  { name: 'Moldova', alpha2: 'md' },
  { name: 'Monaco', alpha2: 'mc' },
  { name: 'Mongolia', alpha2: 'mn' },
  { name: 'Montenegro', alpha2: 'me' },
  { name: 'Morocco', alpha2: 'ma' },
  { name: 'Mozambique', alpha2: 'mz' },
  { name: 'Myanmar', alpha2: 'mm' },
  { name: 'Namibia', alpha2: 'na' },
  { name: 'Nauru', alpha2: 'nr' },
  { name: 'Nepal', alpha2: 'np' },
  { name: 'Netherlands', alpha2: 'nl' },
  { name: 'New Zealand', alpha2: 'nz' },
  { name: 'Nicaragua', alpha2: 'ni' },
  { name: 'Niger', alpha2: 'ne' },
  { name: 'Nigeria', alpha2: 'ng' },
  { name: 'North Korea', alpha2: 'kp' },
  { name: 'North Macedonia', alpha2: 'mk' },
  { name: 'Norway', alpha2: 'no' },
  { name: 'Oman', alpha2: 'om' },
  { name: 'Pakistan', alpha2: 'pk' },
  { name: 'Palau', alpha2: 'pw' },
  { name: 'Palestine', alpha2: 'ps' },
  { name: 'Panama', alpha2: 'pa' },
  { name: 'Papua New Guinea', alpha2: 'pg' },
  { name: 'Paraguay', alpha2: 'py' },
  { name: 'Peru', alpha2: 'pe' },
  { name: 'Philippines', alpha2: 'ph' },
  { name: 'Poland', alpha2: 'pl' },
  { name: 'Portugal', alpha2: 'pt' },
  { name: 'Qatar', alpha2: 'qa' },
  { name: 'Romania', alpha2: 'ro' },
  { name: 'Russia', alpha2: 'ru' },
  { name: 'Rwanda', alpha2: 'rw' },
  { name: 'Saint Kitts and Nevis', alpha2: 'kn' },
  { name: 'Saint Lucia', alpha2: 'lc' },
  { name: 'Saint Vincent and the Grenadines', alpha2: 'vc' },
  { name: 'Samoa', alpha2: 'ws' },
  { name: 'San Marino', alpha2: 'sm' },
  { name: 'Sao Tome and Principe', alpha2: 'st' },
  { name: 'Saudi Arabia', alpha2: 'sa' },
  { name: 'Senegal', alpha2: 'sn' },
  { name: 'Serbia', alpha2: 'rs' },
  { name: 'Seychelles', alpha2: 'sc' },
  { name: 'Sierra Leone', alpha2: 'sl' },
  { name: 'Singapore', alpha2: 'sg' },
  { name: 'Slovakia', alpha2: 'sk' },
  { name: 'Slovenia', alpha2: 'si' },
  { name: 'Solomon Islands', alpha2: 'sb' },
  { name: 'Somalia', alpha2: 'so' },
  { name: 'South Africa', alpha2: 'za' },
  { name: 'South Korea', alpha2: 'kr' },
  { name: 'South Sudan', alpha2: 'ss' },
  { name: 'Spain', alpha2: 'es' },
  { name: 'Sri Lanka', alpha2: 'lk' },
  { name: 'Sudan', alpha2: 'sd' },
  { name: 'Suriname', alpha2: 'sr' },
  { name: 'Sweden', alpha2: 'se' },
  { name: 'Switzerland', alpha2: 'ch' },
  { name: 'Syria', alpha2: 'sy' },
  { name: 'Taiwan', alpha2: 'tw' },
  { name: 'Tajikistan', alpha2: 'tj' },
  { name: 'Tanzania', alpha2: 'tz' },
  { name: 'Thailand', alpha2: 'th' },
  { name: 'Togo', alpha2: 'tg' },
  { name: 'Tonga', alpha2: 'to' },
  { name: 'Trinidad and Tobago', alpha2: 'tt' },
  { name: 'Tunisia', alpha2: 'tn' },
  { name: 'Turkey', alpha2: 'tr' },
  { name: 'Turkmenistan', alpha2: 'tm' },
  { name: 'Tuvalu', alpha2: 'tv' },
  { name: 'Uganda', alpha2: 'ug' },
  { name: 'Ukraine', alpha2: 'ua' },
  { name: 'United Arab Emirates', alpha2: 'ae' },
  { name: 'United Kingdom', alpha2: 'gb' },
  { name: 'United States', alpha2: 'us' },
  { name: 'Uruguay', alpha2: 'uy' },
  { name: 'Uzbekistan', alpha2: 'uz' },
  { name: 'Vanuatu', alpha2: 'vu' },
  { name: 'Vatican City', alpha2: 'va' },
  { name: 'Venezuela', alpha2: 've' },
  { name: 'Vietnam', alpha2: 'vn' },
  { name: 'Yemen', alpha2: 'ye' },
  { name: 'Zambia', alpha2: 'zm' },
  { name: 'Zimbabwe', alpha2: 'zw' },
];

// Alpha-2 to ISO 3166-1 numeric code mapping (for globe highlighting)
export const ALPHA2_TO_NUMERIC: Record<string, string> = {
  'af':'004','al':'008','dz':'012','ad':'020','ao':'024','ag':'028','ar':'032','am':'051',
  'au':'036','at':'040','az':'031','bs':'044','bh':'048','bd':'050','bb':'052','by':'112',
  'be':'056','bz':'084','bj':'204','bt':'064','bo':'068','ba':'070','bw':'072','br':'076',
  'bn':'096','bg':'100','bf':'854','bi':'108','cv':'132','kh':'116','cm':'120','ca':'124',
  'cf':'140','td':'148','cl':'152','cn':'156','co':'170','km':'174','cd':'180','cg':'178',
  'cr':'188','hr':'191','cu':'192','cy':'196','cz':'203','dk':'208','dj':'262','dm':'212',
  'do':'214','tl':'626','ec':'218','eg':'818','sv':'222','gq':'226','er':'232','ee':'233',
  'sz':'748','et':'231','fj':'242','fi':'246','fr':'250','ga':'266','gm':'270','ge':'268',
  'de':'276','gh':'288','gr':'300','gd':'308','gt':'320','gn':'324','gw':'624','gy':'328',
  'ht':'332','hn':'340','hu':'348','is':'352','in':'356','id':'360','ir':'364','iq':'368',
  'ie':'372','il':'376','it':'380','ci':'384','jm':'388','jp':'392','jo':'400','kz':'398',
  'ke':'404','ki':'296','xk':'383','kw':'414','kg':'417','la':'418','lv':'428','lb':'422',
  'ls':'426','lr':'430','ly':'434','li':'438','lt':'440','lu':'442','mg':'450','mw':'454',
  'my':'458','mv':'462','ml':'466','mt':'470','mh':'584','mr':'478','mu':'480','mx':'484',
  'fm':'583','md':'498','mc':'492','mn':'496','me':'499','ma':'504','mz':'508','mm':'104',
  'na':'516','nr':'520','np':'524','nl':'528','nz':'554','ni':'558','ne':'562','ng':'566',
  'kp':'408','mk':'807','no':'578','om':'512','pk':'586','pw':'585','ps':'275','pa':'591',
  'pg':'598','py':'600','pe':'604','ph':'608','pl':'616','pt':'620','qa':'634','ro':'642',
  'ru':'643','rw':'646','kn':'659','lc':'662','vc':'670','ws':'882','sm':'674','st':'678',
  'sa':'682','sn':'686','rs':'688','sc':'690','sl':'694','sg':'702','sk':'703','si':'705',
  'sb':'090','so':'706','za':'710','kr':'410','ss':'728','es':'724','lk':'144','sd':'729',
  'sr':'740','se':'752','ch':'756','sy':'760','tw':'158','tj':'762','tz':'834','th':'764',
  'tg':'768','to':'776','tt':'780','tn':'788','tr':'792','tm':'795','tv':'798','ug':'800',
  'ua':'804','ae':'784','gb':'826','us':'840','uy':'858','uz':'860','vu':'548','va':'336',
  've':'862','vn':'704','ye':'887','zm':'894','zw':'716'
};

// Reverse mapping: numeric code → alpha-2 (derived from ALPHA2_TO_NUMERIC)
export const NUMERIC_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(ALPHA2_TO_NUMERIC).map(([alpha2, num]) => [num, alpha2])
);

// Countries that use MM/DD/YYYY format
export const MDY_COUNTRIES = ['United States', 'Palau', 'Micronesia', 'Marshall Islands'];

export const INTERESTS = [
  { id: 'food', label: 'Food & Dining', icon: '🍕' },
  { id: 'history', label: 'History & Culture', icon: '🏛️' },
  { id: 'nature', label: 'Nature & Outdoors', icon: '🌲' },
  { id: 'adventure', label: 'Adventure Sports', icon: '🧗' },
  { id: 'art', label: 'Art & Museums', icon: '🎨' },
  { id: 'shopping', label: 'Shopping', icon: '🛍️' },
  { id: 'nightlife', label: 'Nightlife', icon: '💃' },
  { id: 'wellness', label: 'Relaxation & Wellness', icon: '🧘' },
  { id: 'photography', label: 'Photography', icon: '📸' },
  { id: 'local', label: 'Local Experiences', icon: '🤝' },
  { id: 'sports', label: 'Sports & Events', icon: '⚽' },
  { id: 'music', label: 'Music & Festivals', icon: '🎸' }
];

export const TRAVEL_GOALS = [
  { id: 'continents', label: 'Visit every continent', icon: '🌍' },
  { id: 'wonders', label: 'See the 7 Wonders', icon: '🗿' },
  { id: 'language', label: 'Learn a new language', icon: '🗣️' },
  { id: 'solo', label: 'Go on a solo trip', icon: '🎒' },
  { id: 'budget', label: 'Travel on a budget', icon: '💰' },
  { id: 'luxury', label: 'Luxury experiences', icon: '💎' },
  { id: 'sustainable', label: 'Sustainable travel', icon: '🌱' },
  { id: 'nomad', label: 'Digital Nomad lifestyle', icon: '💻' }
];

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];
