import React from 'react';
import { Globe as GlobeIcon, ArrowLeft } from 'lucide-react';

const TermsOfService: React.FC<{ onBack: () => void }> = ({ onBack }) => (
  <div className="min-h-screen bg-white">
    <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-gray-100">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-3 sm:py-4 flex items-center gap-3">
        <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-xl transition-colors">
          <ArrowLeft className="w-5 h-5 text-gray-600" />
        </button>
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-green-500 rounded-lg flex items-center justify-center">
            <GlobeIcon className="w-4 h-4 text-white" />
          </div>
          <span className="text-lg font-black text-gray-800">
            Globo<span className="text-green-500">Trotter</span>
          </span>
        </div>
      </div>
    </nav>

    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
      <h1 className="text-3xl sm:text-4xl font-black text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 font-medium mb-10">Last updated: April 4, 2026</p>

      <div className="prose prose-gray max-w-none space-y-8 text-gray-600 leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using GloboTrotter ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">2. Description of Service</h2>
          <p>GloboTrotter is a travel logging and AI-powered trip planning platform. The Service allows you to log trips, visualize travel history on an interactive globe, generate AI-powered itineraries, and earn gamified rewards.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">3. Accounts</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must sign in with a valid Apple or Google account to use the Service.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must be at least 13 years old to use the Service.</li>
            <li>One account per person. Automated or bot accounts are not permitted.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">4. Payments and Subscriptions</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Pro Upgrade ($9.99, one-time):</strong> Grants Pro status and 100 AI planning fuel ("fuel").</li>
            <li><strong>Fuel Refill ($1.99):</strong> Adds 50 AI planning fuel to your account.</li>
            <li>All payments are processed securely by Stripe.</li>
            <li>All sales are final. Refunds are issued at our discretion on a case-by-case basis.</li>
            <li>Prices are in USD and may be subject to change with notice.</li>
            <li>We may introduce new pricing tiers, subscription plans, or updated pricing structures in the future. We will notify existing users before any changes affect their account.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">5. AI-Generated Content</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Itineraries are generated by AI (Anthropic Claude) and are provided for informational and inspirational purposes only.</li>
            <li>We do not guarantee the accuracy, safety, or suitability of AI-generated travel recommendations.</li>
            <li>Always verify travel information (visa requirements, safety advisories, operating hours, etc.) with official sources before traveling.</li>
            <li>GloboTrotter is not a travel agency and does not book flights, hotels, or activities on your behalf.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">6. User Content</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You retain ownership of all content you upload (photos, notes, trip data).</li>
            <li>By uploading content, you grant us a license to store and display it within the Service.</li>
            <li>Do not upload content that is illegal, harmful, or infringes on others' rights.</li>
            <li>We may remove content that violates these terms.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Attempt to manipulate fuel, XP, or other in-app systems.</li>
            <li>Use the Service for any unlawful purpose.</li>
            <li>Attempt to access other users' data or accounts.</li>
            <li>Reverse engineer, scrape, or abuse the Service or its APIs.</li>
            <li>Use automated systems to interact with the Service without permission.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">8. Limitation of Liability</h2>
          <p>The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, GloboTrotter shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to travel disruptions, data loss, or reliance on AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">9. Termination</h2>
          <p>We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting us. Upon termination, your data will be deleted in accordance with our Privacy Policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">10. Changes to Terms</h2>
          <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will notify you of material changes via the app.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">11. Governing Law</h2>
          <p>These Terms are governed by the laws of England and Wales. Any disputes shall be resolved in the courts of England and Wales.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-800 mb-3">12. Contact</h2>
          <p>Questions about these Terms? Contact us at <strong>support@globotrottr.com</strong>.</p>
        </section>
      </div>
    </div>
  </div>
);

export default TermsOfService;
